services:
  app:
    build: .
    container_name: vault-demo-app
    network_mode: host
    environment:
      VAULT_ADDR: http://localhost:8200
      VAULT_TOKEN: 'token-test0'
    restart: unless-stopped
