server:
  port: 8080

spring:
  application:
    name: vault-demo

  # Configuración H2 simple
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ejemplo: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO